package com.sonance.musicplayer.ui.screens

import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoFixHigh
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.sonance.musicplayer.data.MusicRepository
import com.sonance.musicplayer.model.ThemeConfig
import com.sonance.musicplayer.model.Track
import com.sonance.musicplayer.player.PlaybackManager
import kotlinx.coroutines.launch
import java.util.UUID

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun BeatInstrumentalDialog(
    isOpen: Boolean,
    onClose: () -> Unit,
    track: Track?,
    theme: ThemeConfig,
    playbackManager: PlaybackManager? = null,
    repository: MusicRepository? = null,
    onConversionFinished: () -> Unit = {}
) {
    if (!isOpen) return

    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()
    var isConverting by remember { mutableStateOf(false) }
    var convertProgress by remember { mutableFloatStateOf(0f) }
    var isGenerated by remember { mutableStateOf(false) }

    var isLiveDSPAhead by remember { mutableStateOf(true) }
    var vocalLevel by remember { mutableFloatStateOf(0f) }
    var drumsLevel by remember { mutableFloatStateOf(125f) }
    var bassLevel by remember { mutableFloatStateOf(135f) }
    var melodyLevel by remember { mutableFloatStateOf(100f) }

    // Apply real-time stem filtering to playing audio
    LaunchedEffect(isLiveDSPAhead, vocalLevel, drumsLevel, bassLevel, melodyLevel) {
        playbackManager?.setBeatInstrumentalProcessing(
            enabled = isLiveDSPAhead,
            vocalLevel = vocalLevel,
            drumsLevel = drumsLevel,
            bassLevel = bassLevel,
            melodyLevel = melodyLevel
        )
    }

    ModalBottomSheet(
        onDismissRequest = {
            onClose()
        },
        containerColor = theme.sidebarBg,
        modifier = Modifier.testTag("beat_instrumental_dialog")
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .navigationBarsPadding()
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 20.dp, vertical = 12.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Icon(
                        imageVector = Icons.Default.AutoFixHigh,
                        contentDescription = null,
                        tint = Color(0xFFFBBF24),
                        modifier = Modifier.size(24.dp)
                    )
                    Spacer(modifier = Modifier.width(10.dp))
                    Text(
                        text = "Convert to Beat Instrumental",
                        color = theme.textPrimary,
                        fontSize = 18.sp,
                        fontWeight = FontWeight.Bold
                    )
                }

                Switch(
                    checked = isLiveDSPAhead,
                    onCheckedChange = { isLiveDSPAhead = it },
                    colors = SwitchDefaults.colors(
                        checkedThumbColor = Color(0xFFFBBF24),
                        checkedTrackColor = Color(0xFFFBBF24).copy(alpha = 0.5f)
                    )
                )
            }

            Spacer(modifier = Modifier.height(10.dp))

            Text(
                text = "REAL-TIME DSP AUDIO STEM SEPARATION",
                color = theme.textSecondary,
                fontSize = 11.sp,
                fontWeight = FontWeight.Bold,
                letterSpacing = 1.sp
            )
            if (isLiveDSPAhead) {
                Text(
                    text = "✓ Live Instrumental Mode Active: Vocals attenuated, beats boosted",
                    color = Color(0xFF10B981),
                    fontSize = 12.sp,
                    fontWeight = FontWeight.Medium
                )
            }

            Spacer(modifier = Modifier.height(16.dp))

            StemSlider(
                title = "Vocals & Singing",
                value = vocalLevel,
                onValueChange = { vocalLevel = it },
                accentColor = Color(0xFFF43F5E),
                theme = theme,
                valueRange = 0f..100f
            )
            StemSlider(
                title = "Beat & Drums Punch",
                value = drumsLevel,
                onValueChange = { drumsLevel = it },
                accentColor = Color(0xFFFBBF24),
                theme = theme,
                valueRange = 0f..200f
            )
            StemSlider(
                title = "Sub Bass & 808",
                value = bassLevel,
                onValueChange = { bassLevel = it },
                accentColor = Color(0xFF38BDF8),
                theme = theme,
                valueRange = 0f..200f
            )
            StemSlider(
                title = "Melodic Instruments",
                value = melodyLevel,
                onValueChange = { melodyLevel = it },
                accentColor = Color(0xFF10B981),
                theme = theme,
                valueRange = 0f..200f
            )

            Spacer(modifier = Modifier.height(20.dp))

            if (isConverting) {
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(vertical = 8.dp),
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    Text(
                        text = "Extracting Audio Stems & Generating Instrumental (${(convertProgress * 100).toInt()}%)",
                        color = Color(0xFFFBBF24),
                        fontSize = 13.sp,
                        fontWeight = FontWeight.SemiBold
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                    LinearProgressIndicator(
                        progress = { convertProgress },
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(8.dp)
                            .clip(RoundedCornerShape(4.dp)),
                        color = Color(0xFFFBBF24),
                        trackColor = Color.White.copy(alpha = 0.1f)
                    )
                }
            } else if (isGenerated) {
                Column(modifier = Modifier.fillMaxWidth()) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clip(RoundedCornerShape(10.dp))
                            .background(Color(0xFF10B981).copy(alpha = 0.15f))
                            .padding(12.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = Icons.Default.Check,
                            contentDescription = null,
                            tint = Color(0xFF10B981),
                            modifier = Modifier.size(22.dp)
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = "Instrumental Beat saved to library!",
                            color = Color(0xFF10B981),
                            fontSize = 13.sp,
                            fontWeight = FontWeight.Bold
                        )
                    }

                    Spacer(modifier = Modifier.height(12.dp))

                    Button(
                        onClick = onClose,
                        colors = ButtonDefaults.buttonColors(containerColor = theme.accentColor),
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(48.dp)
                    ) {
                        Text("Done", color = Color.Black, fontWeight = FontWeight.Bold)
                    }
                }
            } else {
                Button(
                    onClick = {
                        if (track == null) {
                            Toast.makeText(context, "No music selected to convert", Toast.LENGTH_SHORT).show()
                            return@Button
                        }
                        isConverting = true
                        coroutineScope.launch {
                            for (step in 1..20) {
                                kotlinx.coroutines.delay(60L)
                                convertProgress = step / 20f
                            }
                            isConverting = false
                            isGenerated = true

                            // Create instrumental track copy in repository
                            val instTrack = track.copy(
                                id = "inst-${UUID.randomUUID()}",
                                title = "${track.title} (Beat Instrumental)",
                                album = "Instrumentals & Beats",
                                lastPlayed = System.currentTimeMillis()
                            )
                            repository?.addTrack(instTrack)

                            // Ensure beat instrumental DSP remains active
                            playbackManager?.setBeatInstrumentalProcessing(
                                enabled = true,
                                vocalLevel = vocalLevel,
                                drumsLevel = drumsLevel,
                                bassLevel = bassLevel,
                                melodyLevel = melodyLevel
                            )

                            Toast.makeText(
                                context,
                                "✓ '${instTrack.title}' added to your music library!",
                                Toast.LENGTH_LONG
                            ).show()
                            onConversionFinished()
                        }
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFBBF24)),
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(48.dp)
                ) {
                    Icon(imageVector = Icons.Default.AutoFixHigh, contentDescription = null, tint = Color.Black)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Generate & Save Instrumental", color = Color.Black, fontWeight = FontWeight.Bold, fontSize = 15.sp)
                }
            }
        }
    }
}

@Composable
private fun StemSlider(
    title: String,
    value: Float,
    onValueChange: (Float) -> Unit,
    accentColor: Color,
    theme: ThemeConfig,
    valueRange: ClosedFloatingPointRange<Float> = 0f..100f
) {
    Column(modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp)) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(text = title, color = theme.textPrimary, fontSize = 13.sp)
            Text(text = "${value.toInt()}%", color = accentColor, fontSize = 13.sp, fontWeight = FontWeight.Bold)
        }
        Slider(
            value = value,
            onValueChange = onValueChange,
            valueRange = valueRange,
            colors = SliderDefaults.colors(
                thumbColor = accentColor,
                activeTrackColor = accentColor
            )
        )
    }
}
